/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelas.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author BURHAN NASIR RAUF
 */
public class FLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FUtamaAdmin
     */
    public FLaporan() {
        initComponents();
        try {
            tampil();
        } catch (SQLException ex) {
            Logger.getLogger(FLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void mati(){
        jTable1.setEnabled(false);
        btn_cetak.setEnabled(false);
        btn_hapus.setEnabled(false);
        txt_tanggal.setEnabled(false);
        txt_grade.setEnabled(false);
        txt_kode.setText("");
        txt_persen.setText("");
    }   
    
    private DefaultTableModel tampil() throws SQLException {
        Object header[] ={"Kode", "Grade", "Tanggal", "Persentasi"};
        DefaultTableModel tabel = new DefaultTableModel(null, header);
        String sql = "SELECT * FROM identifikasi WHERE ket='Layak Ekspor' order by kd_tuna asc";
        Connection conn = DBConfig.getKoneksi();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()) {
            String a = rs.getString("kd_tuna");
            String b = rs.getString("grade");
            String c = rs.getString("tanggal");
            String d = rs.getString("persentasi");
            Blob blob = rs.getBlob("foto");
            byte[] data = blob.getBytes(1, (int) blob.length());
            String h = new String(data);
            String kolom[] = {a, b, c, d};
            tabel.addRow(kolom);
            jTable1.setModel(tabel);
        }
        return tabel;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JLabel();
        btn_batal = new javax.swing.JLabel();
        panelGambar4 = new UI.PanelGambar();
        btn_kirim1 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        Keterangan = new javax.swing.JLabel();
        txt_persen = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_grade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        statusbar = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CETAK");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 338, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("BATAL");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 338, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("KIRIM");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 338, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, -1, -1));

        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn-simpan.png"))); // NOI18N
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, -1, 30));

        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn-simpan.png"))); // NOI18N
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, 30));

        panelGambar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelGambar4.setPreferredSize(new java.awt.Dimension(350, 250));

        javax.swing.GroupLayout panelGambar4Layout = new javax.swing.GroupLayout(panelGambar4);
        panelGambar4.setLayout(panelGambar4Layout);
        panelGambar4Layout.setHorizontalGroup(
            panelGambar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        panelGambar4Layout.setVerticalGroup(
            panelGambar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        getContentPane().add(panelGambar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        btn_kirim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn-simpan.png"))); // NOI18N
        btn_kirim1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kirim1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_kirim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, 30));

        txt_kode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_kode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_kode.setEnabled(false);
        getContentPane().add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 150, 30));

        Keterangan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Keterangan.setForeground(new java.awt.Color(255, 255, 255));
        Keterangan.setText("Persentasi");
        getContentPane().add(Keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 226, -1, -1));

        txt_persen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_persen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_persen.setEnabled(false);
        getContentPane().add(txt_persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 150, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("HAPUS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 338, -1, -1));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn-simpan.png"))); // NOI18N
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, 30));

        txt_tanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tanggal.setEnabled(false);
        getContentPane().add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 150, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 1010, 340));

        txt_grade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_grade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_grade.setEnabled(false);
        getContentPane().add(txt_grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Grade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 126, -1, -1));

        statusbar.setBackground(new java.awt.Color(0, 138, 138));
        statusbar.setForeground(new java.awt.Color(0, 138, 138));
        statusbar.setPreferredSize(new java.awt.Dimension(1366, 29));
        statusbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/minimize.jpg"))); // NOI18N
        jButton4.setAlignmentY(1.0F);
        jButton4.setMargin(new java.awt.Insets(2, 13, 2, 15));
        jButton4.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        statusbar.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1308, 2, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        jButton5.setAlignmentY(1.0F);
        jButton5.setMargin(new java.awt.Insets(2, 13, 2, 15));
        jButton5.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        statusbar.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1338, 2, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Laporan Tuna Siap Ekspor");
        statusbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 280, 29));

        getContentPane().add(statusbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/unnamed.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 150, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setState(FLaporan.ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Ingin kembali ke halaman utama ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION) {
            FUtamaAdmin n = new FUtamaAdmin();
            n.show();
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        try {
                JasperDesign jd = JRXmlLoader.load("src/laporan/report1.jrxml");
                JasperReport jr  = JasperCompileManager.compileReport(jd);
                HashMap param = new HashMap();
                JasperPrint jp = JasperFillManager.fillReport(jr, null, DBConfig.getKoneksi());
                JasperViewer jv = new JasperViewer (jp, false);
                jv.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(FLaporan.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.isEnabled()){
            btn_cetak.setEnabled(true);
            btn_hapus.setEnabled(true);
            try {
                int a = jTable1.getSelectedRow();
                txt_kode.setText(jTable1.getValueAt(a, 0).toString());
                String gg = jTable1.getValueAt(a, 1).toString();
                txt_tanggal.setText(jTable1.getValueAt(a, 2).toString());
                txt_persen.setText(jTable1.getValueAt(a, 3).toString()+"%");
                txt_grade.setText("Grade "+gg);
                String sql = "SELECT * FROM identifikasi WHERE kd_tuna ='"+ txt_kode.getText()+"'";
                Connection cn = DBConfig.getKoneksi();
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                if (rs.first()){
                    Blob blob = rs.getBlob("foto");
                    byte[] data = blob.getBytes(1, (int) blob.length());
                    Image gbr = ImageIO.read(new ByteArrayInputStream(data));
                    panelGambar4.setImage(gbr);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FSampel.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (IOException ex) {
                Logger.getLogger(FLaporan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        try {
            String sql = "DELETE FROM idebtifikasi WHERE kd_tuna ='"+ txt_kode.getText()+"'";
            Connection cn = DBConfig.getKoneksi();
            Statement st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Sukses");
        } catch (SQLException ex) {
            Logger.getLogger(FLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_kirim1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kirim1MouseClicked
        if (btn_kirim1.isEnabled()){
            try {
                btn_cetak.setEnabled(true);
                btn_hapus.setEnabled(true);
                String sql = "UPDATE identifikasi SET ket='Telah Ekspor' WHERE kd_tuna ='"+ txt_kode.getText()+"'";
                Connection cn = DBConfig.getKoneksi();
                Statement st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil dikirim");
                mati();
            } catch (SQLException ex) {
                Logger.getLogger(FLaporan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_kirim1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Keterangan;
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel btn_cetak;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_kirim1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private UI.PanelGambar panelGambar4;
    private javax.swing.JPanel statusbar;
    private javax.swing.JTextField txt_grade;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_persen;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
