/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JTextField;
import kelas.*;

/**
 *
 * @author BURHAN NASIR RAUF
 */
public class FLogin extends javax.swing.JFrame {

    /**
     * Creates new form FUtamaAdmin
     */
    public FLogin() {
        initComponents();
        muncul(txt_username);
        muncul(txt_password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void muncul(JTextField tf){
        Font font = tf.getFont();
        font = font.deriveFont(Font.ITALIC);
        tf.setFont(font);
        tf.setForeground(Color.gray);
    }
    
    public void hilang(JTextField tf){
        Font font = tf.getFont();
        font = font.deriveFont(Font.PLAIN);
        tf.setFont(font);
        tf.setForeground(Color.black);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusbar = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusbar.setBackground(new java.awt.Color(0, 138, 138));
        statusbar.setForeground(new java.awt.Color(0, 138, 138));
        statusbar.setPreferredSize(new java.awt.Dimension(1366, 29));
        statusbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/minimize.jpg"))); // NOI18N
        jButton4.setAlignmentY(1.0F);
        jButton4.setMargin(new java.awt.Insets(2, 13, 2, 15));
        jButton4.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        statusbar.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1308, 2, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        jButton5.setAlignmentY(1.0F);
        jButton5.setMargin(new java.awt.Insets(2, 13, 2, 15));
        jButton5.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        statusbar.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1338, 2, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Halaman Login");
        statusbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 280, 29));

        getContentPane().add(statusbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Belum punya akun ? Daftar disini");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 670, -1, -1));

        txt_username.setBackground(new java.awt.Color(0, 255, 255));
        txt_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_username.setText("username");
        txt_username.setBorder(null);
        txt_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 320, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/textbox.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 350, -1));

        txt_password.setBackground(new java.awt.Color(0, 255, 255));
        txt_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_password.setText("password");
        txt_password.setBorder(null);
        txt_password.setEchoChar('\u0000');
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 320, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/textbox.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 350, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Tampilkan password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 310, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 250, 198));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("METODE GLCM DAN K-NN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PENGOLAHAN CITRA DIGITAL UNTUK MENENTUKAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("IKAN TUNA KUALITAS EKSPOR MENGGUNAKAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn-login.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/unnamed.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 150, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setState(FLogin.ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Ingin Menutup Aplikasi ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION) {
            System.exit(0); 
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txt_password.setEchoChar((char)0);
            jCheckBox1.setText("Sembunyikan password");
        } else
        {
            txt_password.setEchoChar((char)42);
            jCheckBox1.setText("Tampilkan password");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        if (txt_username.getText().equals("username")){
            txt_username.setText(null);
            txt_username.requestFocus();
            hilang(txt_username);
        }
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        if (txt_password.getText().equals("password")){
            txt_password.setText(null);
            txt_password.requestFocus();
            txt_password.setEchoChar((char)42);
            hilang(txt_password);
        }
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        if (txt_username.getText().length()==0){
            muncul(txt_username);
            txt_username.setText("username");
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        if (txt_password.getText().length()==0){
            muncul(txt_password);
            txt_password.setEchoChar((char)0);
            txt_password.setText("password");
            jCheckBox1.setSelected(false);
            jCheckBox1.setText("Tampilkan password");
        }
    }//GEN-LAST:event_txt_passwordFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (txt_username.getText().equals("username")) {
            JOptionPane.showMessageDialog(null, "Masukkan username");
            txt_username.requestFocus();
        } else
        if (txt_password.getText().equals("password")) {
            JOptionPane.showMessageDialog(null, "Masukkan password");
            txt_password.requestFocus();
        } else
        if (txt_username.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan username");
            txt_username.requestFocus();
        } else
        if (txt_password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan password");
            txt_password.requestFocus();
        } else
        {
            try {
                Connection cn = DBConfig.getKoneksi();
                Statement st = cn.createStatement();
                String sql = "SELECT * FROM user WHERE username='"+txt_username.getText()+"' and password='"
                             +txt_password.getText()+"'";
                ResultSet rs = st.executeQuery(sql);
                FUtamaAdmin admin = new FUtamaAdmin();
                FUtamaNelayan nelayan = new FUtamaNelayan();
                simpan a = new simpan();
                if (rs.next()) {
                    if (rs.getString("level").equals("1")){
                        a.setUsername(rs.getString("username"));
                        admin.show();
                        this.dispose();
                    } else
                    if (rs.getString("level").equals("2")){
                        a.setUsername(rs.getString("username"));
                        nelayan.show();
                        this.dispose();
                    }
                    
                    Calendar timestamp = new GregorianCalendar();
                    int tahun = timestamp.get(Calendar.YEAR);
                    int bulan = timestamp.get(Calendar.MONTH)+1;
                    int hari = timestamp.get(Calendar.DAY_OF_MONTH);
                    int jam = timestamp.get(Calendar.HOUR_OF_DAY);
                    int menit = timestamp.get(Calendar.MINUTE);
                    int detik = timestamp.get(Calendar.SECOND);
                    String waktu = tahun+"-"+bulan+"-"+hari+" "+jam+":"+menit+":"+detik;
                    
                    String url = "UPDATE user SET sesi='"+waktu+"' WHERE username='"+txt_username.getText()+"'";
                    st.executeUpdate(url);
                } else {
                    JOptionPane.showMessageDialog(null, "Username/password salah!");
                    txt_password.requestFocus();
                    txt_password.selectAll();
                }
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(this, e);
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        FRegis n = new FRegis();
        n.show();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel statusbar;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
